### ISSUE TITLE
What is your preferred line-length limit?

### ISSUE THREAD

**Issue by skilkis** [TUDelft-CNS-ATM/EduBot#12]
The code-quality improvements made in #11 allow us to specify the line-length that the project should adhere to (along with many other style enforcements). Personally I like following PEP-8 guidelines (79 characters for code, 72 characters for docstrings) but this is easy to change for both flake8 and Black. What should be the line-length limit for this project?

After reaching an agreement, errors from flake8 that enforce this can be re-enabled in the CI pipeline.

**Comment by jooste** [comment]
I myself am not too strict. I try to adhere to 80 characters, but for some code lines line breaking makes the code so unreadable that I sometimes do leave them longer than 80 chars.
